-- 01_CREATE_OBJECTS.sql
CREATE DATABASE IF NOT EXISTS RETAIL_DWH;
USE DATABASE RETAIL_DWH;

CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS RAW_DV;
CREATE SCHEMA IF NOT EXISTS BUSINESS_DV;
CREATE SCHEMA IF NOT EXISTS METADATA;

-- File format for ADLS CSVs
CREATE OR REPLACE FILE FORMAT STAGING.CSV_FORMAT
TYPE='CSV'
FIELD_OPTIONALLY_ENCLOSED_BY='"'
SKIP_HEADER=1;

-- External stage pointing to ADLS (replace URL & creds)
CREATE OR REPLACE STAGE STAGING.AZURE_STAGE
URL='azure://<your-adls-container>.blob.core.windows.net/raw-data/'
FILE_FORMAT = STAGING.CSV_FORMAT;

-- Metadata tables
CREATE OR REPLACE TABLE METADATA.JOB_AUDIT (
    JOB_NAME STRING,
    SCRIPT_NAME STRING,
    STATUS STRING,
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ,
    RECORD_COUNT INT,
    COMMENTS STRING
);
