-- 02_STAGE_LOAD.sql
USE DATABASE RETAIL_DWH;

CREATE OR REPLACE TABLE STAGING.STG_SALES (
    SALE_ID STRING,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    SALE_DATE DATE,
    AMOUNT NUMBER(10,2)
);

-- Example COPY INTO from ADLS
COPY INTO STAGING.STG_SALES
FROM @STAGING.AZURE_STAGE/sales_data/
FILE_FORMAT = (FORMAT_NAME = STAGING.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- Log entry
INSERT INTO METADATA.JOB_AUDIT
SELECT 'STAGING_LOAD', '02_STAGE_LOAD.sql', 'SUCCESS', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), COUNT(*), 'Loaded from ADLS'
FROM STAGING.STG_SALES;
