-- 03_DV_LOAD.sql
USE DATABASE RETAIL_DWH;

-- HUB_CUSTOMER
CREATE OR REPLACE TABLE RAW_DV.HUB_CUSTOMER (
    HUB_CUSTOMER_KEY STRING,
    CUSTOMER_ID STRING,
    RECORD_SOURCE STRING,
    LOAD_DATETIME TIMESTAMP_NTZ
);

-- SAT_SALES
CREATE OR REPLACE TABLE RAW_DV.SAT_SALES (
    HUB_CUSTOMER_KEY STRING,
    PRODUCT_ID STRING,
    SALE_DATE DATE,
    AMOUNT NUMBER(10,2),
    LOAD_DATETIME TIMESTAMP_NTZ,
    RECORD_SOURCE STRING
);

-- Load Hub
INSERT INTO RAW_DV.HUB_CUSTOMER
SELECT DISTINCT
    SHA1(CUSTOMER_ID),
    CUSTOMER_ID,
    'ADLS_SALES',
    CURRENT_TIMESTAMP()
FROM STAGING.STG_SALES;

-- Load Satellite
INSERT INTO RAW_DV.SAT_SALES
SELECT
    SHA1(CUSTOMER_ID),
    PRODUCT_ID,
    SALE_DATE,
    AMOUNT,
    CURRENT_TIMESTAMP(),
    'ADLS_SALES'
FROM STAGING.STG_SALES;

-- Audit log
INSERT INTO METADATA.JOB_AUDIT
SELECT 'DV_LOAD', '03_DV_LOAD.sql', 'SUCCESS', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), COUNT(*), 'Hubs & Sats populated'
FROM RAW_DV.SAT_SALES;
