-- 04_BUSINESS_VIEWS.sql
USE DATABASE RETAIL_DWH;

CREATE OR REPLACE VIEW BUSINESS_DV.VW_CUSTOMER_SALES AS
SELECT
    H.CUSTOMER_ID,
    SUM(S.AMOUNT) AS TOTAL_SALES,
    COUNT(DISTINCT S.PRODUCT_ID) AS DISTINCT_PRODUCTS,
    MAX(S.SALE_DATE) AS LAST_PURCHASE_DATE
FROM RAW_DV.HUB_CUSTOMER H
JOIN RAW_DV.SAT_SALES S
  ON H.HUB_CUSTOMER_KEY = S.HUB_CUSTOMER_KEY
GROUP BY H.CUSTOMER_ID;

INSERT INTO METADATA.JOB_AUDIT
SELECT 'BUSINESS_VIEWS', '04_BUSINESS_VIEWS.sql', 'SUCCESS', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), COUNT(*), 'Views created'
FROM BUSINESS_DV.VW_CUSTOMER_SALES;
